### ISSUE TITLE
I want to be able to host the api and the web frontend on the same route

### ISSUE THREAD

**Issue by CraftingDragon007** [KekOnTheWorld/uploadserver#5]
The following happens, when you specify the same base url for both
![image](https://user-images.githubusercontent.com/68032198/154822808-e0eb9e30-0beb-490a-942c-965806315fc5.png)

**Comment by lbirkert** [comment]
This happens because the api has an index route too. If you want i can move this to /about

**Comment by lbirkert** [comment]
It is prefered if you move this entirely to another route base because else your frontend might collide with the api routes.

**Comment by lbirkert** [comment]
I quickly checked and rocket does not support such automatic collision fixes even if you move the index route or delete it entirely. If you really need such feature consider using a nginx reverse proxy.
